### ISSUE TITLE
Question about GCC not being on path inside Docker container

### ISSUE THREAD

**Issue by jvkersch** [bioconda/bioconda-recipes#11458]
This is my first recipe, so I might be overlooking something really obvious. I'm trying to build a recipe for a Python package that requires GCC (full recipe [here](https://github.com/jvkersch/bioconda-recipes/tree/enh/parasail-recipe)).

I can build the package locally with `conda-build`, but whenever I try to build it inside a Docker container with `circleci build`, the recipe fails because GCC could not be found. I've verified that GCC is installed in `./opt/rh/devtoolset-2/root/usr/lib/gcc` inside the Docker container.

My question is: do I need to do anything special (setting PATH, ...) beyond adding `- {{ compiler('c') }}` to my build requirements? 

Here is my requirements section:
```
requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
  host:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy
```

This is the path as it appears in my container `PATH=/usr/bin:/opt/conda/conda-bld/parasail_1540117162163/_build_env/bin:/opt/conda/conda-bld/parasail_1540117162163/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin:/opt/conda/conda-bld/parasail_1540117162163/_build_env:/opt/conda/conda-bld/parasail_1540117162163/_build_env/bin:/root/project/miniconda/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
