### ISSUE TITLE
hg not installed

### ISSUE THREAD

**Issue by bebatut** [bioconda/bioconda-recipes#1175]
Hi,

I have a package (`export2graphlan`) with  `meta.yaml`
```
about:
    home: 'https://bitbucket.org/CibioCM/export2graphlan/overview'
    summary: "export2graphlan is a conversion software tool for producing both annotation and tree file for GraPhlAn"
package:
  name: export2graphlan
  version: "0.1"
build:
  number: 0
  skip: False
source:
  hg_url: https://hg@bitbucket.org/CibioCM/export2graphlan
  hg_tag: tip
requirements:
  run:
      - python 2.7*
      - matplotlib
      - pandas 0.13*
      - scipy
test:
  commands:
      - export2graphlan.py -h
```

When I run `docker run -v `pwd`:/bioconda-recipes bioconda/bioconda-builder --packages export2graphlan`, I get `Error: hg not installed` 
Does this issue may come from the `Dockerfile` with non installation of `mercurial`?

Bérénice
