### ISSUE TITLE
Rhdf5 should be build against the conda HDF5 package

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#12402]
## Task: 

EDIT: It turned out that the issue is that rhdf5 comes with its own hdf5 packaged. If you then try to read an HDF5 file written by a newer version of hdf5, it can crash like seen above. To avoid such incompatibilities, we should try to build rhdf5 with the conda hdf5 package.

## Original text:
It seems like I cannot read HDF5 files with the latest rhdf5 from bioconda:
```
h5read("testthat/small_test_data/kallisto/abundance.h5", "bootstrap/bs1")
Error in H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  : 
  HDF5. Dataset. Read failed.
NULL
```

The file is from [here](https://github.com/pachterlab/sleuth/tree/master/tests/testthat/small_test_data/kallisto), and can be read without problems using system hdfview.
Has anybody seen this as well?

**Comment by johanneskoester** [comment]
ping @bioconda/core

**Comment by johanneskoester** [comment]
This is the verbose version of the error message:
```
Error in H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  : 
  libhdf5
    error #000: 0� in (): line 223
        class: HDF5
        major: Dataset
        minor: Read failed
    error #-06: ��j in ��(): line 605
        class: HDF5
        major: Dataset
        minor: Read failed
    error #-05: 0�V in �aY(): line 2092
        class: HDF5
        major: Low-level I/O
        minor: Read failed
    error #-04:  'S in 0��(): line 3122
        class: HDF5
        major: Data filters
        minor: Filter operation failed
    error #-03: �_ in (): line 1345
        class: HDF5
        major: Data filters
        minor: Read failed
    error #-02: ��\ in �n<(): line 380
        class: HDF5
        major: Plugin for dynamically loaded library
        minor: Can't get value
    error #-01: � in ��u(): line 738
        class: HDF5
        major: Plugin for dynamically loaded library
        minor: Can't open directory or file
In addition: Warning message:
In strsplit(msg, "\n") : input string 1 is invalid in this locale
NULL
```
Looks like it cannot load a library?

**Comment by johanneskoester** [comment]
It turned out that the issue is that rhdf5 comes with its own hdf5 packaged. If you then try to read an HDF5 file written by a newer version of hdf5, it can crash like seen above. To avoid such incompatibilities, we should try to build rhdf5 with the conda hdf5 package.

**Comment by johanneskoester** [comment]
Okay, another revision. It is not a bug in rhdf5 or rhdf5lib. Rather, it seems to be related to how we build our package. The package from icm-iconics works fine: https://anaconda.org/icm-iconics/bioconductor-rhdf5lib.

Now, they weirdly include a lot of dependencies there, and I can't believe they are all needed. THis is the recipe:
```
# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# /network/lustre/dtlake01/bioinfo/support_data/PIPELINES/dev/Bistar/git/recipes/RHDF5Lib/recipe, last modified Thu Nov 29 10:07:55 2018
# ------------------------------------------------

package:
    name: bioconductor-rhdf5lib
    version: 1.4.1
source:
    url: https://bioconductor.org/packages/release/bioc/src/contrib/Rhdf5lib_1.4.1.tar.gz
build:
    number: '0'
    rpaths:
        - lib/
        - lib/R/lib/
    string: r351
requirements:
    build:
        - autoconf 2.69 2
        - automake 1.14 1
        - libgcc-ng 7.2.0 hdf63c60_3
        - m4 1.4.18 h470a237_1
        - make 4.2.1 h470a237_1002
        - perl 5.26.0 hae598fd_0
        - toolchain 2.3.0 0
        - toolchain_c_linux-64 2.3.0 0
    host:
        - _r-mutex 1.0.0 anacondar_1
        - blas 1.1 openblas
        - bwidget 1.9.11 1
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.10.15 ha4d7672_0
        - cairo 1.14.12 h276e583_5
        - curl 7.62.0 h74213dd_0
        - fontconfig 2.13.1 h65d0f4c_0
        - freetype 2.9.1 h6debe1e_4
        - gettext 0.19.8.1 h5e8e0c9_1
        - glib 2.56.2 h464dc38_1
        - graphite2 1.3.12 hfc679d8_1
        - gsl 2.2.1 blas_openblashddceaf2_6
        - harfbuzz 1.9.0 h04dbb29_1
        - icu 58.2 hfc679d8_0
        - jpeg 9c h470a237_1
        - krb5 1.16.2 hbb41f41_0
        - libcurl 7.62.0 hbdb9355_0
        - libedit 3.1.20170329 haf1bffa_1
        - libffi 3.2.1 hfc679d8_5
        - libgcc-ng 7.2.0 hdf63c60_3
        - libgfortran 3.0.0 1
        - libiconv 1.15 h470a237_3
        - libpng 1.6.35 ha92aebf_2
        - libssh2 1.8.0 h5b517e9_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - libtiff 4.0.9 he6b73bb_2
        - libuuid 2.32.1 h470a237_2
        - libxcb 1.13 h470a237_2
        - libxml2 2.9.8 h422b904_5
        - make 4.2.1 h470a237_1002
        - ncurses 6.1 hfc679d8_1
        - openblas 0.3.3 ha44fe06_1
        - openssl 1.0.2p h470a237_1
        - pango 1.40.14 he752989_2
        - pcre 8.41 hfc679d8_3
        - pixman 0.34.0 h470a237_3
        - pthread-stubs 0.4 h470a237_1
        - r-base 3.5.1 h391c2eb_4
        - readline 7.0 haf1bffa_1
        - tk 8.6.9 ha92aebf_0
        - tktable 2.10 h14c3975_0
        - xorg-kbproto 1.0.7 h470a237_2
        - xorg-libice 1.0.9 h470a237_4
        - xorg-libsm 1.2.3 h8c8a85c_0
        - xorg-libx11 1.6.6 h470a237_0
        - xorg-libxau 1.0.8 h470a237_6
        - xorg-libxdmcp 1.1.2 h470a237_7
        - xorg-libxext 1.3.3 h470a237_4
        - xorg-libxrender 0.9.10 h470a237_2
        - xorg-libxt 1.1.5 h470a237_2
        - xorg-renderproto 0.11.1 h470a237_2
        - xorg-xextproto 7.3.0 h470a237_2
        - xorg-xproto 7.0.31 h470a237_7
        - xz 5.2.4 h470a237_1
        - zlib 1.2.11 h470a237_3
    run:
        - autoconf
        - automake
        - bzip2
        - bzip2 >=1.0.6,<2.0a0
        - ca-certificates
        - cairo
        - cairo >=1.14.12,<2.0a0
        - curl
        - fontconfig
        - fontconfig >=2.13.1,<3.0a0
        - freetype
        - freetype >=2.9.1,<3.0a0
        - gettext
        - gettext >=0.19.8.1,<1.0a0
        - glib
        - glib >=2.56.2,<3.0a0
        - graphite2
        - gsl
        - gsl >=2.2.1,<2.3.0a0
        - harfbuzz
        - icu
        - jpeg
        - jpeg >=9c,<10a
        - krb5
        - krb5 >=1.16.2,<1.17.0a0
        - libffi
        - libffi >=3.2.1,<4.0a0
        - libgcc-ng
        - libgcc-ng >=4.9
        - libgfortran
        - libiconv
        - libiconv >=1.15,<2.0a0
        - libpng
        - libpng >=1.6.35,<1.7.0a0
        - libssh2
        - libssh2 >=1.8.0,<2.0a0
        - libstdcxx-ng
        - libtiff
        - libtiff >=4.0.9,<5.0a0
        - libuuid
        - libuuid >=2.32.1,<3.0a0
        - libxcb
        - libxml2
        - libxml2 >=2.9.8,<2.10.0a0
        - m4
        - make
        - ncurses
        - openssl
        - openssl >=1.0.2p,<1.0.3a
        - pango
        - pcre
        - pcre >=8.41,<9.0a0
        - perl
        - pixman
        - pixman >=0.34.0,<1.0a0
        - pthread-stubs
        - r-base 3.5.1
        - readline
        - readline >=7.0,<8.0a0
        - tk
        - tk >=8.6.9,<8.7.0a0
        - toolchain
        - toolchain_c_linux-64
        - xorg-kbproto
        - xorg-libice
        - xorg-libsm
        - xorg-libx11
        - xorg-libxau
        - xorg-libxdmcp
        - xorg-libxext
        - xorg-libxrender
        - xorg-libxt
        - xorg-renderproto
        - xorg-xextproto
        - xorg-xproto
        - xz
        - xz >=5.2.4,<6.0a0
        - zlib
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - $R -e "library('Rhdf5lib')"
about:
    home: http://bioconductor.org/packages/3.8/bioc/html/Rhdf5lib.html
    license: Artistic-2.0
    summary: Provides C and C++ hdf5 libraries.
extra:
    copy_test_source_files: true
    final: true
```
