### ISSUE TITLE
How to use gcc7 in meta.yaml for osx

### ISSUE THREAD

**Issue by zhanxw** [bioconda/bioconda-recipes#12446]
I want to use the gcc7 from condo-forge to compile my C++ source codes in mac OS X (https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml).

How to specify gcc7 in meta.yaml?

**Comment by zhanxw** [comment]
No need to use gcc7 for the support of OpenMP.

Use these to enable openmp for Mac OSX:

```
requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - clangdev  # [osx]
    - libcxx 4.0.*  # [osx]
    - openmp 4.0.*  # [osx]
  run:
    - libcxx >=4.0  # [osx]
    - openmp >=4.0  # [osx]
```
