### ISSUE TITLE
Need some guidance: build won't complete

### ISSUE THREAD

**Issue by betteridiot** [bioconda/bioconda-recipes#12848]
## Setup
* OS: Ubuntu 14.04 (64-bit)
* python: 3.6.7
* conda: 4.5.12
* conda-build: 3.15.1

### Setup the environment
```bash
# Setup environment
conda create -n bioconda_seqlogo python=3.7 numpy=1.15.0 pandas=0.23.4 pytest=4.0.2 twine conda conda-build weblogo=3.6.0  
conda activate bioconda_seqlogo
```
### Setup the fork
```bash
git clone https://github.com/betteridiot/bioconda-recipes.git
cd bioconda-recipes
git remote add upstream https://github.com/bioconda/bioconda-recipes.git
git checkout -b seqlogo
cd recipes/
```
### Build the recipe
```bash
conda skeleton pypi --version=0.1.12 seqlogo
cd seqlogo
```
## Now the meta.yaml
```yaml
{% set name = "seqlogo" %}
{% set version = "0.1.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256:  b172a4b52ea406d1b3225e3e6a580e69b435f2e69a9e1e94c68cf982e948ccb7

build:
  skip: True # [py27]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - numpy
    - pandas
    - pytest
    - python
    - weblogo
    - ghostscript

test:
  imports:
    - seqlogo
  requires:
    - pytest
  commands:
    - {{ PYTHON }} -m pytest --pyargs seqlogo

about:
  home: https://github.com/betteridiot/seqlogo
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Python port of the R Bioconductor `seqlogo` package

extra:
  recipe-maintainers:
    - betteridiot
```
* then I added my [LICENSE](https://github.com/betteridiot/seqlogo/blob/master/LICENSE) to the recipe

## Circle CI results
Every time it gets to the tests, it cannot find [pytest to run the test command](https://circleci.com/gh/bioconda/bioconda-recipes/39087) or it gets a [permission error for a README.md file](https://circleci.com/gh/bioconda/bioconda-recipes/39089). 

## Workaround 
Once I removed my the `requires` and `commands` section under `test`, I no longer had a problem. What am I doing wrong here?
