### ISSUE TITLE
Use svn url as source in yaml file

### ISSUE THREAD

**Issue by shunhuahan** [bioconda/bioconda-recipes#14105]
- I'm trying to create recipe for R package h5r. The package is currently maintained in a SVN repository. I used `svn_url` and `svn_rev` in the `meta.yaml` file according to guidelines from https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html. Local `conda build` works fine, but `circleci build` can not recognize `svn_rev` and would throw `missing_hash` error. 
- I searched around and looks like I can not download a tar/zip packaged repo from svn. Is there any way to get around this issue?
- This is my `meta.yaml` file.
```
{% set name = 'h5r' %}
{% set version = 'v1.4.9' %}

package:
  name: r-{{ name }}
  version: {{ version|replace("-", "_") }}

source:
  svn_url: svn://svn.r-forge.r-project.org/svnroot/h5r/
  svn_rev: 97
  svn_ignore_externals: False # (defaults to False)

build:
  number: 0
  skip: False
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - r-base
    - hdf5
  run:
    - r-base
    - hdf5

test:
    commands:
      - '$R -e "library(''{{ name }}'')"'

about:
    home: http://r-forge.r-project.org/projects/h5r/
    license: LGPL
```
