### ISSUE TITLE
setup.py: command not found

### ISSUE THREAD

**Issue by endrebak** [bioconda/bioconda-recipes#15181]
When I try to build a package (NCLS) using the `build: script:` tag using the autogenerated command from `conda skeleton pypi ncls`, namely

```
build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip:
    True # [osx]
```

circleci fails with the message `/opt/conda/conda-bld/ncls_1557313438451/work/conda_build.sh: line 4: setup.py: command not found`

What am I doing wrong? Here is the log:

https://circleci.com/gh/bioconda/bioconda-recipes/55886

Here is the file that fails: https://github.com/bioconda/bioconda-recipes/pull/15179/files
