### ISSUE TITLE
Help with a recipe that requires libGL

### ISSUE THREAD

**Issue by nfahlgren** [bioconda/bioconda-recipes#15556]
Hi all, I'm stuck and looking for some help. I am updating the recipe for `plantcv` (a pure Python package) and I am stuck getting tests to pass because one of our dependencies, `opencv`, requires `libGL`. The pull request is #15539 for reference.

I'm running the mulled-tests using: `bioconda-utils build recipes config.yml --docker --mulled-test --git-range master`. For brevity I will not post the full output here (here's a link to a full log on CircleCI: https://circleci.com/gh/bioconda/bioconda-recipes/58494). The core part of the error during the recipe tests is:

```
21:23:50 BIOCONDA INFO (OUT) import: 'plantcv'
21:23:50 BIOCONDA INFO (OUT) import: 'plantcv.learn'
21:23:50 BIOCONDA INFO (OUT)     import cv2
21:23:50 BIOCONDA INFO (OUT) ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

I have done a few things to make sure `libGL` is present.

First, I followed the [conda-forge instructions](https://conda-forge.org/docs/maintainer/knowledge_base.html#libgl) for including libGL, my requirements section looks like this:

```
requirements:
  build:
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - python
    - pip
    - xorg-libxfixes
  run:
    - python
    - matplotlib >=1.5
    - numpy >=1.11
    - pandas
    - python-dateutil
    - scipy <1.3
    - scikit-image <0.15
    - plotnine
    - opencv <4
```

Second, I have the recipe configured to use the [extended base container](https://bioconda.github.io/troubleshooting.html#using-the-extended-image):

```
extra:
  container:
    extended-base: true
```

My understanding is that the extended-base alone should be all that's needed because we do not need libGL to build the Python package. I have tried every variation I can think of though.

Anyone have any ideas?
