### ISSUE TITLE
Recipe (auto)formatting?

### ISSUE THREAD

**Issue by tomkinsc** [bioconda/bioconda-recipes#162]
I've been playing with Go lang lately, and enjoying how [`gofmt`](https://golang.org/cmd/gofmt/) produces code of consistent style. As a new user of the language, the uniformity of style makes existing code and examples more accessible and easier to read. 

Conda recipes are short, but I wonder if we should perhaps suggest that recipe authors autoformat their recipes using something like [YAML lint](http://www.yamllint.com/). We could go so far as to automatically format (and commit) recipes upon being merged with `master`, though this may make the commit history a bit messy. I would also be happy to format existing recipes myself, via YAML lint or via a custom script that could be added to the repository. 

YAML lint orders keys alphabetically by default (and also strips out comments), which is perhaps not best for conda recipes. If we were to autoformat recipes in another way, it may make sense to follow the ordering used in the examples given in the [conda docs](http://conda.pydata.org/docs/building/meta-yaml.html), since these are likely to be the ones new contributors refer to when creating new recipes:

``` yaml
package:
  name: pyinstrument
  version: "0.13.1"

source:
  git_rev: 0.13.1
  git_url: https://github.com/joerick/pyinstrument.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pyinstrument

about:
  home: https://github.com/joerick/pyinstrument
  license: BSD
  license_file: LICENSE
```

What do you think? Is this a waste of effort, or would there be benefit to having bioconda recipes formatted in a consistent way?
