### ISSUE TITLE
Error: bad character '-' in package/version: smrtanalysis-3.0.2

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#2993]
Hi,
`conda build` caused this error `Error: bad character '-' in package/version: smrtanalysis-3.0.2` with the below recipie:

```
{% set name = "GenomicConsensus" %}
{% set version = "smrtanalysis-3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}_{{ version }}.tar.gz
  url: https://github.com/PacificBiosciences/GenomicConsensus/archive/{{ version }}.tar.gz
```

What did I do wrong?

Thank you in advance.

Mic
