### ISSUE TITLE
pytest not found during mulled-build

### ISSUE THREAD

**Issue by jlumpe** [bioconda/bioconda-recipes#29967]
The CircleCI job for my [PR](https://github.com/bioconda/bioconda-recipes/pull/29965) keeps failing on the mulled-build stage with the f[ollowing line](https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/50965/workflows/5e6e6c48-c84f-4477-81dc-7eaef221968b/jobs/164640?invite=true#step-106-696):

    00:36:37 BIOCONDA INFO (ERR) [Aug  9 00:36:37] SERR bash: pytest: command not found

The `test` part of my recipe is

```yaml
test:
  requires:
    - pytest
  source_files:
    - tests
  imports:
    - gambit
  commands:
    - pytest
    - gambit --help
 ```

The tests run fine during the initial build stage. I noticed that during the package installation part of this stage `pytest` is installed, but it doesn't appear during mulled-build.
