### ISSUE TITLE
OSError: [Errno 13] Permission denied: '/MaSuRCA-3.2.1_09012016'

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#3017]
Hi, I tried to write a recipe for MaSuRCA as shown below:

meta.yaml
```
{% set name = "masurca" %}
{% set version = "3.2.1_09012016" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}_{{ version }}.tar.gz
  url: ftp://ftp.genome.umd.edu/pub/MaSuRCA/MaSuRCA-{{ version }}.tar.gz

build:
  skip: True # [not py27]

requirements:
  build:
    - perl
    - gcc # [not osx]
    - llvm # [osx]
    - boost

  run:
    - perl
    - boost
    - libgcc  # [not osx]

test:
  commands:
    - variantCaller

about:
  home: https://github.com/PacificBiosciences/GenomicConsensus
  license: BSD-3-Clause
  summary: 'PacBio variant and consensus caller'
```
build.sh
```
#!/bin/bash

./install.sh
```

Unfortunately, I recived the following error:
```
> conda build recipes/masurca/
BUILD START: masurca-3.2.1_09012016-pl5.20.3_0
    (actual version deferred until further download or env creation)
updating index in: /QRISdata/Q0231/apps/conda-bld/linux-64
updating index in: /QRISdata/Q0231/apps/conda-bld/noarch
Using Anaconda API: https://api.anaconda.org

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    perl-5.20.3.1              |                1        14.0 MB  conda-forge
    xz-5.2.2                   |                0         853 KB  conda-forge
    mpfr-3.1.4                 |                2         402 KB  conda-forge
    python-3.5.2               |                2        31.4 MB  conda-forge
    boost-1.62.0               |           py35_0        17.5 MB  conda-forge
    certifi-2016.9.26          |           py35_0         217 KB  conda-forge
    setuptools-28.8.0          |           py35_0         366 KB  conda-forge
    wheel-0.29.0               |           py35_0          82 KB  conda-forge
    pip-9.0.1                  |           py35_0         1.8 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        66.6 MB

The following NEW packages will be INSTALLED:

    boost:           1.62.0-py35_0    conda-forge
    ca-certificates: 2016.9.26-0      conda-forge
    certifi:         2016.9.26-py35_0 conda-forge
    cloog:           0.18.0-0                    
    gcc:             4.8.5-7                     
    gmp:             6.1.1-1          conda-forge
    icu:             56.1-4           conda-forge
    isl:             0.12.2-0                    
    mpc:             1.0.3-1          conda-forge
    mpfr:            3.1.4-2          conda-forge
    ncurses:         5.9-9            conda-forge
    openssl:         1.0.2h-2         conda-forge
    perl:            5.20.3.1-1       conda-forge
    pip:             9.0.1-py35_0     conda-forge
    python:          3.5.2-2          conda-forge
    readline:        6.2-0            conda-forge
    setuptools:      28.8.0-py35_0    conda-forge
    sqlite:          3.13.0-1         conda-forge
    tk:              8.5.19-0         conda-forge
    wheel:           0.29.0-py35_0    conda-forge
    xz:              5.2.2-0          conda-forge
    zlib:            1.2.8-3          conda-forge

WARNING:/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/build.pyc:Build prefix failed with prefix length 255
WARNING:/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/build.pyc:Error was: 
WARNING:/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/build.pyc:ERROR: placeholder '/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho' too short in: conda-forge::ncurses-5.9-9

WARNING:/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/build.pyc:One or more of your package dependencies needs to be rebuilt with a longer prefix length.
WARNING:/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/build.pyc:Falling back to legacy prefix length of 80 characters.
WARNING:/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/build.pyc:Your package will not install into prefixes > 80 characters.
updating index in: /QRISdata/Q0231/apps/conda-bld/linux-64
updating index in: /QRISdata/Q0231/apps/conda-bld/noarch

The following NEW packages will be INSTALLED:

    boost:           1.62.0-py35_0    conda-forge
    ca-certificates: 2016.9.26-0      conda-forge
    certifi:         2016.9.26-py35_0 conda-forge
    cloog:           0.18.0-0                    
    gcc:             4.8.5-7                     
    gmp:             6.1.1-1          conda-forge
    icu:             56.1-4           conda-forge
    isl:             0.12.2-0                    
    mpc:             1.0.3-1          conda-forge
    mpfr:            3.1.4-2          conda-forge
    ncurses:         5.9-9            conda-forge
    openssl:         1.0.2h-2         conda-forge
    perl:            5.20.3.1-1       conda-forge
    pip:             9.0.1-py35_0     conda-forge
    python:          3.5.2-2          conda-forge
    readline:        6.2-0            conda-forge
    setuptools:      28.8.0-py35_0    conda-forge
    sqlite:          3.13.0-1         conda-forge
    tk:              8.5.19-0         conda-forge
    wheel:           0.29.0-py35_0    conda-forge
    xz:              5.2.2-0          conda-forge
    zlib:            1.2.8-3          conda-forge

/usr/bin/ld: skipping incompatible /usr/lib/../lib/libc.so when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libc.so when searching for -lc
Source cache directory is: /QRISdata/Q0231/apps/conda-bld/src_cache
Downloading source to cache: masurca_3.2.1_09012016.tar.gz
Downloading ftp://ftp.genome.umd.edu/pub/MaSuRCA/MaSuRCA-3.2.1_09012016.tar.gz
Success
Extracting download
Traceback (most recent call last):
  File "/QRISdata/Q0231/apps/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 247, in main
    execute(sys.argv[1:])
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 239, in execute
    already_built=None, config=config, noverify=args.no_verify)
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/api.py", line 77, in build
    need_source_download=need_source_download, config=config)
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/build.py", line 1088, in build_tree
    config=recipe_config)
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/build.py", line 652, in build
    config=config)
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/render.py", line 86, in parse_or_try_download
    source.provide(metadata.path, metadata.get_section('source'), config=config)
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/source.py", line 485, in provide
    unpack(meta, config=config)
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/source.py", line 84, in unpack
    tar_xf(src_path, config.work_dir)
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/utils.py", line 270, in tar_xf
    t.extractall(path=dir_path)
  File "/QRISdata/Q0231/apps/lib/python2.7/tarfile.py", line 2079, in extractall
    self.extract(tarinfo, path)
  File "/QRISdata/Q0231/apps/lib/python2.7/tarfile.py", line 2116, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/QRISdata/Q0231/apps/lib/python2.7/tarfile.py", line 2194, in _extract_member
    self.makedir(tarinfo, targetpath)
  File "/QRISdata/Q0231/apps/lib/python2.7/tarfile.py", line 2222, in makedir
    os.mkdir(targetpath, 0700)
OSError: [Errno 13] Permission denied: '/MaSuRCA-3.2.1_09012016'
```

What did I do wrong?

Thank you in advance.

Mic

**Comment by bgruening** [comment]
Try to match the `fn` name the downloaded file name.

**Comment by mictadlo** [comment]
Hi, I changed it to:
```
{% set name = "MaSuRCA" %}
{% set version = "3.2.1_09012016" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: ftp://ftp.genome.umd.edu/pub/MaSuRCA/{{ name }}-{{ version }}.tar.gz
```

Unfortunately, I still get the same error. 

What did I miss?

Thank you in advance.

Michal
