### ISSUE TITLE
Perl GD module

### ISSUE THREAD

**Issue by daler** [bioconda/bioconda-recipes#326]
GD is a dependency of `circos` and `fastq_screen`. Below are my notes on what I've tried in order to create a recipe for it.

Easy way first:

```bash
conda skeleton cpan GD
# Using url https://cpan.metacpan.org/authors/id/L/LD/LDS/GD-2.56.tar.gz (273441) for GD.
# Processing dependencies for GD......Fetching package metadata: ......
# done
# Writing recipe for perl-gd-2.56
# Done
```
`conda skeleton cpan` adds core (built-in) Perl modules to the dependencies. Comment them out. We also need the `libgd` conda package. Here's the stripped-down meta.yaml:

```yaml
package:
  name: perl-gd
  version: "2.56"
source:
  fn: GD-2.56.tar.gz
  url: https://cpan.metacpan.org/authors/id/L/LD/LDS/GD-2.56.tar.gz
  md5: c4b3afd98b2c4ce3c2e1027d101a8f1e
requirements:
  build:
    - perl
    - libgd
    #- perl-module-build
    #- perl-math-complex
    #- perl-extutils-cbuilder
  run:
    - perl
    - libgd
    #- perl-math-complex
test:
  imports:
    - GD
    - GD::Group
    - GD::Polygon
    - GD::Polyline
    - GD::Simple
about:
  home: http://metacpan.org/pod/GD
  license: perl_5
  summary: 'Perl interface to the gd2 graphics library'
```

Building fails because Module::Build is out of date:
```bash
conda build perl-gd-2.56/
#
# ...snip...
#
# Module::Build version 0.42 required--this is only version 0.4003 at ./Build line 41.
```

Hmm, maybe try the regular Makefile.PL in the build script. I commented out the 
```bash
if [ -f Build.PL ]; then
...
```
section in the build.sh to make it use the Makefile.PL clause, and try again. Nope:
``` bash
# ...snip...
# Can't create bdf2gdfont.pl: Permission denied at bdf_scripts/bdf2gdfont.PLS line 11.
```
Turns out that's a [known bug](https://rt.cpan.org/Public/Bug/Display.html?id=99901) and the solution is to use Build.PL. That is, the solution is to use the part I just commented out because it was giving old version errors.

Turns out Perl 5.18.2 (the default conda version) included Module::Build as a core module but it is no longer a core module in Perl 5.22.0 (latest version on CPAN). OK, let's build the newer package for Perl 5.18.2:

```
conda skeleton cpan Module::Build
# Using url http://cpan.metacpan.org/authors/id/L/LE/LEONT/Module-Build-0.4003.tar.gz (307352) for Module-Build.
#Writing recipe for perl-module-build-0.4003
# Done
```
Doh, it's pulling that out-of-date version from MetaCPAN. Turns out you can force a version, so try the latest on CPAN:

```bash
conda skeleton cpan Module::Build --version 0.4214
# Using url https://cpan.metacpan.org/authors/id/L/LE/LEONT/Module-Build-0.4214.tar.gz (305051) for # Module-Build.
# Processing dependencies for Module-Build....Fetching package metadata: ......
...............................done
# Writing recipe for perl-module-build-0.4214
# Done
```
The green bars on the [dependencies page](http://deps.cpantesters.org/?module=Module%3A%3ABuild&perl=5.18.2&os=any+OS) for Module::Build v0.4214 indicate all further dependencies needed. Rather than build all those dependencies, let's go back to trying to build GD using a later version of Perl.

```bash
conda install -c bioconda 'perl==5.22.0'
export CONDA_PERL='5.22.0'  # using the --perl 5.22.0 arg to conda build didn't work
conda build perl-gd-2.56
# ...snip...
# Can't locate Module/Build.pm in @INC (you may need to install the Module::Build module)
```
Right, it's not included in this Perl version any more. So let's build the Module::Build v0.4214 after stripping out all dependencies, since in Perl 5.22.0 they're [not needed](http://deps.cpantesters.org/?module=Module%3A%3ABuild&perl=5.22.0&os=any+OS).

```bash
conda build perl-module-build-0.4214
```
Seems to build OK, except for these test results complaining that there's no compiler found (?)
```
t/notes.t ...................... ok     
t/par.t ........................ skipped: No compiler found
t/parents.t .................... ok     
t/perl_mb_opt.t ................ ok   
t/pod_parser.t ................. ok     
t/ppm.t ........................ skipped: No compiler found
t/properties/dist_suffix.t ..... ok   
```

Now add `perl-module-build` to the build dependencies of `perl-gd-2.56/meta.yaml`, and try building:
```bash
conda build perl-gd-2.56
# ...snip...
# Error: no compiler detected to compile 'lib/GD.c'.  Aborting
```

Digging through some source, I figured out the test errors in Module::Build complaining about no compiler were from a call to ExtUtils::CBuilder. The following Perl 5.22.0 code demonstrates the issue:

```perl
#/usr/bin/env perl
use ExtUtils::CBuilder;
my $b = ExtUtils::CBuilder->new(%options);
print $b->have_compiler;
```

    cc: error: unrecognized command line option ‘-fstack-protector-strong’

It appears that this is an option added to GCC 4.9, and apparently the built-in ExtUtils::CBuilder is expecting that flag. My guess is that it is related to [this](
http://perldoc.perl.org/perl5215delta.html#Perl-is-now-compiled-with--fstack-protector-strong-if-available) change in 5.21.

(that's as far as I've gotten so far)
