### ISSUE TITLE
bwakit 0.7.17.dev1 - not using bwakit 0.7.17

### ISSUE THREAD

**Issue by keiranmraine** [bioconda/bioconda-recipes#34098]
Just looking into some bwakit processing and I've noticed that the current closest approximation to an up to date version of bwakit has bwakit-0.7.15 as it was using the sourceforge bundles:

https://github.com/bioconda/bioconda-recipes/blob/8931900ac899cff7dcdae5d5072aaeaeae765775/recipes/bwakit/meta.yaml#L6-L14

I believe it would be more appropriate to simplify to just the bwa repository as this _**includes the bwakit folder**_ (and there are updates between 0.7.15 and 0.7.17):

```yaml
source:
    folder: bwa-0.7.17
    sha256: 980b9591b61c60042c4a39b9e31ccaad8d17ff179d44d347997825da3fdf47fd
    patches:
      - patches/run-HLA.patch
```

I believe some work will be needed on the `build.sh` script too.

Relates to: https://github.com/bioconda/bioconda-recipes/pull/22820
