### ISSUE TITLE
Samwell unexpected python version constraint

### ISSUE THREAD

**Issue by nh13** [bioconda/bioconda-recipes#35688]
Hi everyone, I am trying to figure out why the recipe for [samwell](https://bioconda.github.io/recipes/samwell/README.html) has such stringent Python version requirements: `python >=3.6,<3.7.0a0`.  In contrast, it looks like anaconda has builds for 3.6, 3.7, 3.8, and 3.9 ([link](https://anaconda.org/bioconda/samwell/files)).  I don't see anything in the recipe that forces 3.6.  And I don't understand why anaconda doesn't build for 3.10 either.  Maybe it's a transitive dependency?  But I am a novice at debugging or investigating how/why these constraints are set.  Any help from recipe authors or maintainers would be helpful.

**Comment by siebrenf** [comment]
Dependency hell.

I tried building the recipe locally and got an error from pip check: seems defopts 6.3 requires python >=3.8, but did not specify this in their recipe. Pinning defopts to >=6.3 and python to >=3.8, the build tool wanted to use a higher version of Python than available (bioconda currently builds up to 3.9). 

After toying with the recipe, I got one that works with python 3.9 (but not 3.8 for some reason):

```
{% set name = "samwell" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/samwell-{{ version }}.tar.gz
  sha256: a95c9df5cf6a6d163269aac0b04c37ecac13c725ff131e31b65f0d830c5ffbf1

build:
  number: 1
  script: python -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python >=3.8,<=3.9
    - cython
    - poetry
  run:
    - cython
    - typing_extensions >=3.7.4
    - typing_inspect >=0.3.1
    - attrs >=19.3.0
    - defopt >=6.3
    - mypy_extensions >=0.4.3
    - pybedlite >=0.0.1
    - pysam >=0.15.3
    - python >=3.8,<=3.9

test:
  imports:
    - samwell
    - samwell.sam
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/samwell/
  summary: Useful utilities for biological data formats and analyses
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nh13
    - tfenne
    - NatPRoach
```

Notes:
- I removed some cython related stuff that seemed outdated. If this is correct, you can also remove the patch file.
- Not sure if the `script` changes matter.

This might not be the perfect solution, since its only working in python 3.9, but it might help you find a more permanent solution :) good luck!
