### ISSUE TITLE
r-spp 1.13 installation incomplete / docs incomplete

### ISSUE THREAD

**Issue by mpi-pebert** [bioconda/bioconda-recipes#3788]
Hi,
I just set up a conda environment for running several peak callers like this:

```yaml
name: pkcall
channels:
  - bioconda
  - r 
dependencies:
  - python=2.7
  - numpy=1.11.2
  - macs2=2.1.1
  - samtools=1.3.*
  - r-spp=1.13
```
Installation appears to be successful, yet I cannot find the `run_spp.R` file (following the [phantompeaktools tutorial](https://code.google.com/archive/p/phantompeakqualtools), section about "Typical Usage")

```bash
(pkcall):$ Rscript run_spp.R
Fatal error: cannot open file 'run_spp.R': No such file or directory

../conda/envs:$ find pkcall/ -type f -name "*spp*"
pkcall/lib/R/library/spp/libs/spp.so
pkcall/lib/R/library/spp/help/spp.rdb
pkcall/lib/R/library/spp/help/spp.rdx
pkcall/lib/R/library/spp/R/spp.rdb
pkcall/lib/R/library/spp/R/spp.rdx
pkcall/lib/R/library/spp/R/spp
pkcall/conda-meta/r-spp-1.13-r3.2.2_0.json
```
I have no clue where this file should be located, and the [recipe](http://bioconda.github.io/recipes/r-spp/README.html) does not provide any additional information. What am I missing?

Thanks for your help.
Peter
