### ISSUE TITLE
test_linux couldn't find the test command

### ISSUE THREAD

**Issue by alipirani88** [bioconda/bioconda-recipes#40257]

**Comment by alipirani88** [comment]
I am trying to submit a new bioconda recipe but the test_linux fails to find the test command. Any idea what i am doing wrong?

here is the log 
https://dev.azure.com/bioconda/25074ded-3133-43ca-af80-895ab87b53cb/_apis/build/builds/30997/logs/22

Here is the Bioconda recipe
```
{% set name = "snpkit" %}
{% set version = "Beta2.0.1" %}
{% set sha256 = "e9e2fc5486a8a73dfd7ec921544852b496673f4716dfaaa4552c1162d2054a6c" %}
{% set user = "alipirani88" %}

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  url: 'https://github.com/{{ user }}/{{ name }}/archive/v{{ version }}.tar.gz'
  sha256: '{{ sha256 }}'

build:
  number: 0
  noarch: generic

requirements:
  host:
    - python >=3.6
    - pip
    - pysam >=0.15.2
  run:
    - python >=3.6
    - pysam >=0.15.2
test:
  commands:
    - dist/snpkit -h

about:
  home: 'https://github.com/{{ user }}/{{ name }}'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modular workflow for Microbial Variant Calling and SNP diagnostics.
```
