### ISSUE TITLE
Biopython is not under the MIT license

### ISSUE THREAD

**Issue by peterjc** [bioconda/bioconda-recipes#4399]
From https://github.com/bioconda/bioconda-recipes/blob/master/recipes/biopython/meta.yaml Biopython is wrongly listed as using the MIT license

```yaml
about:
  home: http://www.biopython.org/
  license: MIT
  summary: 'Freely available tools for computational molecular biology.'
  license_family: MIT
```

Biopython uses its own liberal license, the "Biopython License Agreement" (a slight variant of the OSI approved HPND https://opensource.org/licenses/HPND ), but is in the process of transitioning to the more mainstream "3-Clause BSD License", see https://github.com/biopython/biopython/issues/898

I could not find how the ``license_family:`` is defined, or if ``license:`` is a restricted vocabulary. https://conda.io/docs/building/meta-yaml.html#about-section does not say, but does suggest using ``license_file:``. As of Biopython 1.69 you should point at ``LICENSE.rst`` while prior to this release it was just ``LICENSE`` (no extension). See https://github.com/biopython/biopython/blob/master/LICENSE.rst
