### ISSUE TITLE
Sometimes missing license information on anaconda.org

### ISSUE THREAD

**Issue by peterjc** [bioconda/bioconda-recipes#4419]
Consider these examples (mostly tools I am familiar with, picked to show three different licenses):

- https://bioconda.github.io/recipes/khmer/README.html
  - License: BSD-3-Clause
- https://bioconda.github.io/recipes/trackhub/README.html
  - License: BSD 3-clause
- https://bioconda.github.io/recipes/toolshed/README.html
  - License: MIT License
- https://bioconda.github.io/recipes/pyani/README.html
  - License: MIT License
- https://bioconda.github.io/recipes/biopython/README.html
  - License: Biopython License Agreement
- ...

vs

- https://anaconda.org/bioconda/khmer
  - License: BSD-3-Clause (worked!)
- https://anaconda.org/bioconda/trackhub
  - License: BSD 3-clause (worked! Note space not dash as above)
- https://anaconda.org/bioconda/toolshed
  - License: MIT License (worked!)
- https://anaconda.org/bioconda/pyani
  - License: Unspecified (should be MIT)
- https://anaconda.org/bioconda/biopython
  - License: Unspecified (should be Biopython License Agreement)
- ...

Bioconda contains a mix of both "MIT License" and "MIT" (and variants thereof), so initially I wondered if Anaconda.org using a restricted vocabulary - but that alone does not explain the ``toolshed`` vs ``pyani`` example (which differ in their ``license_family`` entry).

Likewise Bioconda contains a mix of both "BSD-3-clause", "BSD 3-clause", "3-Clause BSD", etc - and at least some of the time Anaconda shows them.

Is there a convention used on Anaconda.org about the license metadata which BioConda is not consistently following?

**Comment by daler** [comment]
This is a good point and something that we've not been good about. #1581 was a start at looking at consistency, and once we have a controlled vocabulary we can add it to the linting system to catch issues with new recipes. 

Like you mentioned, anaconda.org seems to be showing "unspecified" if a `license_family` or `license_file` key is included. This seems like an anaconda.org bug.

I'm not aware of any license list that anaconda.org uses. Though I guess when there's a question we could use the "SPDX short identifier" from OSI, so for example BSD 3-clause would have dashes as in https://opensource.org/licenses/BSD-3-Clause. Not all licences have those identifiers though.

**Comment by peterjc** [comment]
I agree whatever is breaking seems to be an anaconda.org bug.

I'm not sure if ``license_file`` is important, consider:

Consider these examples:

- https://bioconda.github.io/recipes/wub/README.html showing: ``MPL-2.0``
  https://anaconda.org/bioconda/wub showing ``License: Unspecified``
- https://bioconda.github.io/recipes/nanonet/README.html showing: ``MPL-2.0``
  https://anaconda.org/bioconda/nanonet showing ``License: Unspecified``

Assuming both recipes match the current files on bioconda.github.io and anaconda.org then only one of these uses ``license_file``, but neither has its license shown properly.

```
about:
  home: https://github.com/nanoporetech/wub
  license: MPL-2.0
  license_file: LICENSE.md
  summary: 'Tools and software library developed by the ONT Applications group'
```

vs

```
about:
  home: https://github.com/nanoporetech/nanonet
  license: MPL-2.0
  summary: Nanonet provides recurrent neural network basecalling for Oxford Nanopore MinION data.
```
