### ISSUE TITLE
drompa command test fails

### ISSUE THREAD

**Issue by descostesn** [bioconda/bioconda-recipes#44645]
Hi,

I am testing locally the following recipe (meta.yaml) with the command `bioconda-utils build --git-range master --packages drompa`:

```
{% set version = "3.7.2" %}

package:
  name: drompa3
  version: {{ version }}


source:
  url: https://github.com/rnakato/DROMPA3/archive/refs/tags/v{{version}}.tar.gz
  sha256: 48aa8a5144e190b92e1c2c53c7782723584d8e923f563a58cc2beec08822fb94

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - gtk2
    - gsl
    - samtools
    - zlib
    - r-base

test:
  commands:
    - parse2wig

about:
  home: https://github.com/rnakato/DROMPA3
  license: GNU General Public License v2.0
  summary: DROMPA can be used for multiple analyses of ChIP-seq data
```

However, it does not manage to find the command `parse2wig`. I am wondering if this is because the uncompressed file is in uppercase `DROMPA3-3.7.2` ? The linting tells me however that I cannot use an uppercase package name.

I have also tested the building with and without the following `build.sh`:

```
#!/bin/bash                                                                                                                                                

git clone git@github.com:coherentgraphics/cpdf-binaries.git

export PATH=$PATH:$HOME/DROMPA3-3.7.2:$HOME/cpdf-binaries/Linux-Intel-64bit/
```

Any help will be greatly appreciated. Thanks.
