### ISSUE TITLE
New recipe conflicting with itself

### ISSUE THREAD

**Issue by ozagordi** [bioconda/bioconda-recipes#4918]
Hi.

I'm trying to contrbute a new recipe for a tool and I 'm having hard time understanding the following error. I'm at the `conda build` step, so when I give `conda build recipes/minvar` it returns the error
```
...
TEST START: /home/ubuntu/miniconda3/conda-bld/linux-64/minvar-1.2a0-py35_0.tar.bz2
Deleting work directory, /home/ubuntu/miniconda3/conda-bld/minvar_1496850276861/work/MinVar-1.2.alpha
Can't build /home/ubuntu/bioconda-recipes/recipes/minvar due to environment creation error:
The following specifications were found to be in conflict:
  - minvar 1.2a0 py35_0
Use "conda info <package>" to see the dependencies for each package.
```

The meta file is

```
ubuntu@min-recipe:~/bioconda-recipes$ cat recipes/minvar/meta.yaml
package:
  name: minvar
  version: "1.2a0"

build:
  number: 0
  skip: True # [py27]

source:
  url: https://github.com/ozagordi/MinVar/archive/v1.2.alpha.tar.gz
  md5: b1fad79d2444ef67382a58ba33f4ce61

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive

  run:
    - biopython
    - blast >=2.3
    - bwa
    #- entrez-direct
    #- htslib
    - lofreq
    - pandas
    - pandoc
    #- prinseq
    - python
    #- r-ggplot2
    - samtools >=1.3
    - seqtk
    - setuptools_scm_git_archive

about:
  home: https://git.io/minvar
  summary: 'A tool to detect minority variants in HIV-1 populations'
  license: Custom
```
Any idea?

Thanks.
    Osvaldo

**Comment by daler** [comment]
There's a known bug in conda where it doesn't correctly report what the conflicting dependency is. My guess is that one of the requirements here is not available for py35. If I remember correctly Biopython had issues with numpy segfaulting on py35 (again, outside the control of bioconda), so anything that depends on biopython will have this issue.

The fix might be to change:

```yaml
build:
  number: 0
  skip: True # [py27]
```
to
```yaml
build:
  number: 0
  skip: True # [py27 or py35]
```
