### ISSUE TITLE
linting error test on Travis although test passes locally

### ISSUE THREAD

**Issue by zachcp** [bioconda/bioconda-recipes#4976]
Hi Team Bioconda,

I really like the  the linting system for catching errors and improving quality. However, I am encountering an issue with the testing code on a simple python-only package that builds/tests fine locally.  

Do you have any idea why the test behavior would differ on Travis? The offending yaml is pasted below and can also be found here (https://github.com/bioconda/bioconda-recipes/pull/4975).  Suggestions on how to modify this file are greatly appreciated.

Thanks,
zach cp

cc/@bioconda/core

The error message:
![screen shot 2017-06-16 at 11 15 51 am](https://user-images.githubusercontent.com/1260667/27232819-66d0d0dc-5285-11e7-89e3-c5ccfe844a0f.png)

```
# test passes locally
+ source /Users/zach/anaconda3/bin/activate /Users/zach/anaconda3/conda-bld/schema_1497626342143/_t_env
+ /Users/zach/anaconda3/conda-bld/schema_1497626342143/_t_env/bin/python -s /Users/zach/anaconda3/conda-bld/schema_1497626342143/test_tmp/run_test.py
import: 'schema'
TEST END: /Users/zach/anaconda3/conda-bld/noarch/schema-0.6.6-py_0.tar.bz2
INFO:conda_build.config:--dirty flag not specified.  Removing build folder after successful build/test.

```

```
package:
  name: schema
  version: "0.6.6"

source:
  fn: schema-0.6.6.tar.gz
  url: https://pypi.python.org/packages/05/5c/25b7fccf722d579d1368415db031dbefedbbddac125363f7827af6aa5ece/schema-0.6.6.tar.gz
  md5: 0da19403e5e2abd49e323b0c076dde18

requirements:
  build:
    - python
    - setuptools

  run:
    - python

build:
  number: 0
  noarch: python
  
test:
  imports:
    - schema

about:
  home: https://github.com/keleshev/schema
  license: MIT License
  summary: 'Simple data validation library'


```
