### ISSUE TITLE
Package request: OGRI (Overall Genome Relatedness Indices)

### ISSUE THREAD

**Issue by tuefue** [bioconda/bioconda-recipes#51707]
Please make package for OGRI:
https://gitlab.pasteur.fr/GIPhy/OGRI

Thanks.

**Comment by tuefue** [comment]
My first try:

meta.yaml
```
{% set version = "1.2" %}

package:
  name: ogri
  version: {{ version }}

source:
  url: https://gitlab.pasteur.fr/GIPhy/OGRI/-/archive/{{ version }}/OGRI-{{ version }}.tar.gz
  sha256: 1d9b198c841948b34c643c81fce70e60f24f8eda3aea5b4a1ed1ebe9ecff0a48

build:
  number: 0

requirements:
  run:
    - gawk >4.0.0
    - prodigal >=2.6.3
    - blast >=2.12.0

test:
  commands:
    - OGRI_B.sh -h

about:
  home: https://gitlab.pasteur.fr/GIPhy/OGRI
  summary: Overall Genome Relatedness Indices
  license: AGPL
```

build.sh
```
#!/bin/bash

mkdir -p $PREFIX/bin
cp OGRI_B.sh $PREFIX/bin
```

What do you think?
