### ISSUE TITLE
Set LC_ALL and LANG env vars in extended base image

### ISSUE THREAD

**Issue by ewels** [bioconda/bioconda-recipes#5842]
See previous discussion at #5541, #5369, #5249, #4811 and others.

#### TL;DR;
The `click` package and others require a locale to be set to work properly with Python 3. The normal busybox image doesn't support locales, but the extended-base image does. However, they appear to either not be set, or something strange is happening with them.

After a bunch of trial and error, the MultiQC build seems to pass with the following setup:

```yaml
commands:
  - LC_ALL=C.UTF-8 LANG=C.UTF-8 multiqc --version # [linux]
  - LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 multiqc --version # [osx]
extra:
  container:
    extended-base: true
```

It would great if the locale settings are set so that `LC_ALL` and `LANG` don't have to be set by the recipes themselves.

Note that linux and OSX require different locale strings to be set currently.

Phil
