### ISSUE TITLE
Can't build packages that contain CONDA_* variables in meta.yaml

### ISSUE THREAD

**Issue by biocyberman** [bioconda/bioconda-recipes#7233]
I am trying to build `ensemble_vep` as discussed in #7186. All packages i have tried failed to build because they have CONDA_* variables in the meta.yaml file. For example, similar things happened to `htslib`, `samtools` and `ensemble_vep`. But `star` package could be built successfully.

Prepare build environment:
```
conda update conda
conda install conda-build patchelf
```

```
conda build htslib  
Undefined Jinja2 variables remain (['CONDA_BZIP2', 'CONDA_BZIP2']).  Please enable source downloading and try again.  
```
Conda version;

```
conda --version 
conda 4.3.30

```

Conda info:

```
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.19
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /home/user/bin/opt/mc3  (writable)
    default environment : /home/user/bin/opt/mc3
       envs directories : /home/user/bin/opt/mc3/envs
                          /home/user/.conda/envs
          package cache : /home/user/bin/opt/mc3/pkgs
                          /home/user/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.12.4 CPython/3.6.0 Linux/4.8.15-1 Funtoo Linux - baselayout /2.2.1 glibc/2.23    
                UID:GID : 1008:1009
```

conda config --show  
```
conda config --show  
add_anaconda_token: True
add_pip_as_python_dependency: True
allow_non_channel_urls: True
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: False
anaconda_upload: None
auto_update_conda: True
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
create_default_packages: []
custom_channels:
  pkgs/main: https://repo.continuum.io/
  pkgs/free: https://repo.continuum.io/
  pkgs/r: https://repo.continuum.io/
  pkgs/pro: https://repo.continuum.io/
  home/user/bin/opt/mc3/conda-bld: file:///
custom_multichannels:
  defaults: ["https://repo.continuum.io/pkgs/main", "https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.continuum.io/pkgs/pro"]
  local: ["file:///home/user/bin/opt/mc3/conda-bld"]
default_channels:
  - https://repo.continuum.io/pkgs/main
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
disallow: []
envs_dirs:
  - /home/user/bin/opt/mc3/envs
  - /home/user/.conda/envs
force: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
non_admin_enabled: True
offline: False
path_conflict: clobber
pinned_packages: []
pkgs_dirs:
  - /home/user/bin/opt/mc3/pkgs
  - /home/user/.conda/pkgs
proxy_servers: {}
quiet: False
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
rollback_enabled: True
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
use_pip: True
verbosity: 0

```

conda config --show-sources gives empty output.
