### ISSUE TITLE
BioTools annotations in BioConda Recipes

### ISSUE THREAD

**Issue by ypriverol** [bioconda/bioconda-recipes#7699]
Hi @contributors, we have started adding some crosslink/references to metadata services for each of our conda recipes. This will work will be done in collaboration with the biocontainer community. Please, can you leave your opinion there? @bgruening @johanneskoester

**Comment by ypriverol** [comment]
Hi all: 
We would like to implement something like this in conda: 

```yml
extra:
  identifiers:
      - biotools:abyss
      - doi:10.1021/ac303239g
      - pmid: 23448308
```
