### ISSUE TITLE
Building gemBS

### ISSUE THREAD

**Issue by guillaumecharbonnier** [bioconda/bioconda-recipes#8463]
I would like to build gemBS but I don't know what to do to ensure binaries are correctly installed.

```bash
#!/bin/bash
git clone --recursive https://github.com/heathsc/gemBS.git
cd gemBS

sed -i "s|/apps/GSL/2.4|$PREFIX|g" tools/bs_call/Gsl.mk

$PYTHON setup.py install
```

```yaml
build:
  number: 1
  #string: gsl{{CONDA_GSL}}_{{PKG_BUILDNUM}}
  skip: True # [osx]
  detect_binary_files_with_prefix: True

package:
  name: gembs
  version: "1"

#source:
#  git_url: https://github.com/heathsc/gemBS

build:
  rpaths:
    - lib/
    - lib/R/lib/

requirements:
  build:
    - python >=2.7,<3
    - gcc
    - git
    - curl
    - gsl

  run:
    - python >=2.7,<3
    - matplotlib
    - gsl

#test:
#  commands:
#    - R -h

about:
  home: https://github.com/heathsc/gemBS
  license: GNU GPL
  summary: GEMBS is a bioinformatic pipeline designed for hightroughput analysis of DNA methylation from whole genome bisulfites sequencing data (WGBS). It implements GEM3, a high performance read aligner and BScall, a variant caller specifically for bisulfite sequencing data. The manuscript describing the pipeline is available at https://www.biorxiv.org/content/early/2017/10/11/201988
```
