### ISSUE TITLE
Recipe failing circleci build with cryptic error

### ISSUE THREAD

**Issue by Carldeboer** [bioconda/bioconda-recipes#8519]
When testing my recipe with circleci build, I'm getting the following error:
```
TEST START: /opt/conda/conda-bld/linux-64/ruby-dna-tools-1.0-py36_0.tar.bz2
Deleting work directory, /opt/conda/conda-bld/ruby-dna-tools_1522772510333/work/Ruby-DNA-Tools-1.0
Can't build /root/project/recipes/ruby-dna-tools due to environment creation error:

  - ruby-dna-tools 1.0 py36_0
  - jemalloc 4.4
  - ruby-dna-tools 1.0 py36_0
  - ruby 2.4
  - ruby 2.4
  - jemalloc 4.4
```
Up until that point, everything seems to work fine.

If I include ruby 2.4 and jemalloc 4.4 in the build requirements, it gives this error instead:
```
BUILD START: ruby-dna-tools-1.0-py35_0
    (actual version deferred until further download or env creation)
Can't build /root/project/recipes/ruby-dna-tools due to unsatisfiable dependencies:

  - ruby 2.4
  - jemalloc 4.4
```

My meta.yaml file is as follows:
```
{% set version = "1.0" %}
{% set sha256 = "9d593872715bf510e66163267ce14e1208ecbdd7017695738610f25b74930f9b" %}

package:
  name: ruby-dna-tools
  version: {{ version }}

source:
  fn: ruby-dna-tools_{{ version }}.tar.gz
  url: https://github.com/Carldeboer/Ruby-DNA-Tools/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - python
    - yaml
  run:
    - ruby 2.4
    - jemalloc 4.4
    - python

test:
    commands:
      - ruby -e 'require "UTILS.rb";'

about:
  home: https://github.com/Carldeboer/Ruby-DNA-Tools
  license: GPL-2.0
  summary: Various libraries containing useful functions for working with DNA sequences, written in ruby. Some tools are not specific to DNA.
```
and build.sh:
```
#!/bin/bash
libloc="$PREFIX/lib/ruby/site_ruby"
mkdir -p $libloc
cp ./*.rb $libloc/.
```

I have tried doing local builds of this recipe as follows, with no problems:
```
conda build  -c conda-forge -c bioconda ruby-dna-tools
```
and then tested it by loading it into a conda environment and running tests manually.  Mind you, this was with a newer version of anaconda (4.5).
Any ideas are much appreciated!
