### ISSUE TITLE
Building with oracle jdk (jfx )

### ISSUE THREAD

**Issue by lindenb** [bioconda/bioconda-recipes#8540]
Hi all,
first time here.

I'm trying to write a recipe for my java-based package _jvarkit_. Some tools require the **jfx** package wich is not included in openjdk.  That is why I've defined my yaml (https://github.com/lindenb/bioconda-recipes/blob/56cbb513248b5efa4f3656f6852495eb10308d38/recipes/jvarkit/2018.04.05/meta.yaml )  using **java-jdk**:

```
(...)
  build:
      - java-jdk >=8,<9
      - (...)
  run:
      - java-jdk >=8,<9
      - (...)
(...)
extra:
   skip-lints:
     - uses_javajdk
```

However, it seems that I still cannot compile my sources (`javafx.scene.canvas does not exist`) as if the java compiler was not the oracle jdk.
 
https://circleci.com/gh/lindenb/bioconda-recipes/36

```
$javafx.scene.canvas does not exist
import javafx.scene.canvas.GraphicsContext;
                          ^
/opt/conda/conda-bld/jvarkit_1522955849324/work/jvarkit-2018.04.05/src/main/jav$
                        final GraphicsContext g,
                              ^
  symbol:   class GraphicsContext
  location: class Hershey
2 errors
```

what am i doing wrong ?

thanks
.
