### ISSUE TITLE
Updating PacBio FALCON - dealing with package version naming problem

### ISSUE THREAD

**Issue by peterjc** [bioconda/bioconda-recipes#8945]
Currently the recipe https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pacbio_falcon/meta.yaml for https://anaconda.org/bioconda/pacbio_falcon uses:

```yaml
{% set name = "pacbio_falcon" %}
{% set version = "052016" %}

package:
  name: {{ name }}
  version: {{ version }}

about:
  home: 'https://github.com/PacificBiosciences/FALCON'
  license: "Standard PacBio Open Source License"
  summary: "A set of tools for fast aligning long reads for consensus and assembly"

source:
  fn: funzip_052016.tar.gz
  url: https://github.com/PacificBiosciences/FALCON/archive/funzip_052016.tar.gz
  md5: be4a225262ee4bd9729b6b7e81a83615

...
```

The https://github.com/PacificBiosciences/FALCON/ repository only currently has tags for ``v0.1``, ``v0.2`` and ``funzip_052016`` which seems to be the latest tag:

https://github.com/PacificBiosciences/FALCON/tree/funzip_052016

That was presumably how things stood when the recipe was first written (@bebatut Jan 2017):

https://github.com/bioconda/bioconda-recipes/commit/fd53551df5042f2d554504c752216fcb0cf390a1#diff-9cd1477e255f1bcb7b1f395abbdf2d30

The README is outdated https://github.com/PacificBiosciences/FALCON/issues/637 but if I understand correctly releases since have been via https://github.com/PacificBiosciences/FALCON-integrate which includes tags for ``0.2.0``, ``0.3.0``, ..., ``2.1.1``, ``2.1.2``, ``2.1.4`` which appears to be the latest.

It would appear that the tag ``funzip_052016`` (i.e. May 2016, sadly not year month order for sorting) was never intended to be regarded as a version number, and instead the ``major.minor.revision`` pattern is being used.

Unfortunately, we now have a BioConda package with version ``052016`` - how will this behave if we try to package FALCON v2.1.4 using ``2.1.4`` as the version?

Can we delete or tag the current package in some way as not to be used? Thus far https://anaconda.org/bioconda/pacbio_falcon reports only 416 downloads.
